import {useQuery} from "@apollo/client"
import Capture from "@components/image/capture"
import gql from "graphql-tag"
import type {NextPage} from "next"
import Head from "next/head"
import {Fragment} from "react"
// import Image from "next/image"

const MOVIES_QUERY = gql`
  query movies {
    movies {
      title
      rating
      releaseYear
      comments {
        text
      }
    }
  }
`

const Home: NextPage = () => {
  const {data, error, loading} = useQuery(MOVIES_QUERY, {fetchPolicy: "cache-and-network"})

  if (loading) {
    return <div>Loading ...</div>
  }
  if (error) {
    return <div>Error: {error.message}</div>
  }

  return (
    <Fragment>
      <Head>
        <title>Sick movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Capture />
    </Fragment>
  )
}

export default Home
