import type {NextPage} from "next"
import Head from "next/head"
import Image from "next/image"
import {Children, cloneElement, FC, ReactElement, ReactNode} from "react"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Test>
        <Button />
      </Test>
    </div>
  )
}

const Button = ({newProp}: any) => {
  return <button style={{backgroundColor: newProp.backgroundColor}}>click me</button>
}

let newProp = {
  backgroundColor: "#1560bd",
  textColor: "#ffffff",
  border: "1px solid #cccccc",
  padding: "0.2em",
}
const Test: FC = ({children}) => {
  const list = Children.toArray(children)
  // console.log("children", children, "list", list)

  return (
    <div>
      {Children.map<ReactNode, ReactNode>(children, child => {
        return cloneElement(child as ReactElement<any>, {newProp}, null)
      })}
    </div>
  )
}

export default Home
