import type {GetStaticProps, NextPage} from "next"
import Head from "next/head"
// import Image from "next/image"

import styles from "../styles/Home.module.css"

interface Props {}
const Home: NextPage<Props> = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sick movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
